<a href="https://colab.research.google.com/github/JaiderSantos/metodos1_JaiderSantos_NicolasGomez/blob/main/parcial_1/parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

In [13]:
x = sp.symbols('x')


def laguerre_polynomial(n):
    return sp.exp(x) / sp.factorial(n) * sp.diff((x**n * sp.exp(-x)), x, n)

def encontrar_raices_laguerre(n):
    L_n = laguerre_polynomial(n)
    raices = sp.nroots(L_n, n=15)
    return np.array(raices, dtype=float)

In [20]:
laguerra = laguerre_polynomial(x)
raiz_1 = encontrar_raices_laguerre(1)
raiz_2 = encontrar_raices_laguerre(2)
raiz_3 = encontrar_raices_laguerre(3)
raiz_4 = encontrar_raices_laguerre(4)
raiz_5 = encontrar_raices_laguerre(5)
print(raiz_1)
print(raiz_2)
print(raiz_3)
print(raiz_4)
print(raiz_5)

[1.]
[0.58578644 3.41421356]
[0.41577456 2.29428036 6.28994508]
[0.32254769 1.7457611  4.5366203  9.39507091]
[ 0.26356032  1.41340306  3.59642577  7.08581001 12.64080084]


In [6]:
def GetAllRoots(x, tolerancia = 16):

  Roots = np.array([])

  for i in x:

    root = GetNewtonMethod(Function,Derivative,i)

    if root != False:

      croot = np.round( root, tolerancia)

      if croot not in Roots:
        Roots = np.append(Roots,croot)

  Roots.sort()

  return Roots